# Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: racle-web-deployment
  labels:
    app: racle-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: racle-web
  template:
    metadata:
      name: racle-web
      labels:
        app: racle-web
    spec:
      containers:
        - name: racle-web
          image: sahilg99/racle-web
          ports:
            - containerPort: 5173
---
# backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: racle-backend-deployment
  labels:
    app: racle-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: racle-backend
  template:
    metadata:
      name: racle-backend
      labels:
        app: racle-backend
    spec:
      containers:
        - name: racle-backend
          image: sahilg99/racle-backend
          ports:
            - containerPort: 80
